version: '3.8'


services:
  angular: frontend
    build: client
    ports:
      - "4200:4200"

  express: 'backend'
    build: express-server
    ports:
      - "3000:3000"
    links:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"
